### ISSUE TITLE
目前百度网盘勾选文件，导出菜单就消失了，希望更新一下 js 脚本

### ISSUE THREAD

**Issue by inke3c** [acgotaku/BaiduExporter#469]
该问题必现，几天前出现

**Comment by UnluckyNinja** [comment]
看#465

**Comment by hkbase** [comment]
我遇到的情况跟楼主一样~~，点了网盘里的文件后，那个导航菜单就不见了

**Comment by lyd87880938** [comment]
@hkbase https://github.com/acgotaku/BaiduExporter/issues/465

**Comment by hkbase** [comment]
测过chrome和firefox下，遇到情况一模一样。
推测，应该是百度的页面函数发生变化了。

**Comment by Frank-MJ** [comment]
作者已经更新了扩展程序，你们下载进行安装就OK了

**Comment by leenchan** [comment]
@Frank-MJ where is update?

**Comment by Frank-MJ** [comment]
你没有看到更新日期是两天前嘛
发自网易邮箱大师
在2017年08月14日 19:02，leenchan 写道： @Frank-MJ where is update?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/acgotaku/BaiduExporter","title":"acgotaku/BaiduExporter","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/acgotaku/BaiduExporter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leenchan in #469: @Frank-MJ where is update?"}],"action":{"name":"View Issue","url":"https://github.com/acgotaku/BaiduExporter/issues/469#issuecomment-322162091"}}}

**Comment by hkbase** [comment]
是的，更新到最新版本后，问题解决，谢谢。
