### ISSUE TITLE
文本地址导出到AriaNg显示错误

### ISSUE THREAD

**Issue by bruceyaogit** [acgotaku/BaiduExporter#528]
首先感谢作者！
使用AriaNgv0.3.0，chrome版本 63.0.3239.84安装了最新版插件1.0.1
但是在网盘页面设置中配置了ARIA2 RPC地址后未测试连接成功。
使用文本导出地址，手动在
AriaNgv0.3.0中添加任务时，提示错误
![image](https://user-images.githubusercontent.com/14084223/34036347-e0d664cc-e1bf-11e7-9239-1680841e7d65.png)

**Comment by acgotaku** [comment]
这个软件我也没用过啊。。。
你确定不是自己配置的问题？？？

**Comment by bruceyaogit** [comment]
谢回复。AriaNg的配置没有问题，我添加磁力链和本地种子任务都可以正常执行。就是本插件导出的文本地址显示地址错误
![image](https://user-images.githubusercontent.com/14084223/34087246-ca361464-e3dc-11e7-91be-dda9b439d675.png)

**Comment by bruceyaogit** [comment]
请拨冗帮我查看下哪里出了问题？谢谢！
我是参照@MarIxs 的教程
https://stray.bitcron.com/hiwifi/aria2geejiao-cheng
教程中用的助手是早期版本。按教程中配置助手的方法（直接复制RPC地址），显示连接错误。
![fireshot pro screen capture 001 - - - yun_baidu_com_disk_home_ category_type 2 vmode list](https://user-images.githubusercontent.com/14084223/34089081-a929ff18-e3e8-11e7-8438-927d2d2bcbad.png)

**Comment by acgotaku** [comment]
http://binux.github.io/yaaw/demo/
你试试把你地址输入这个里面 能不你显示版本号码？

**Comment by bruceyaogit** [comment]
这个厉害啊！
![image](https://user-images.githubusercontent.com/14084223/34246392-59a99dd0-e669-11e7-9d4c-128964bcebf2.png)

**Comment by acgotaku** [comment]
@bruceyaogit 如果这个能显示 而插件不可以的话  可能你地址设置了特殊的字符
你可以告诉我目前的设置URL  然后你自己再换个新的token。。。

**Comment by Xiangsong-Guan** [comment]
貌似同样的问题，而且是在几天前突然出现的，在出现问题之前一直是笨笨的浏览器导出下载地址然后手动添加到aria2c中。出现问题之后使用了一些扩展/脚本均有相似的问题：
`2017-12-23 23:28:26.927742 [ERROR] [AbstractCommand.cc:351] CUID#22 - Download aborted. URI=https://d.pcs.baidu.com/file/0a5b6393d9c5125b5e42ebc18bd19474?fid=3341642904-250528-1061801715935247&time=1514042905&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-4TFzZ%2BI6JdGj9MDOJQsgl34OF0g%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=8279329328991083045&dp-callid=0&r=554039205`
`Exception: [AbstractCommand.cc:351] errorCode=29 URI=http://d7.baidupcs.com/file/0a5b6393d9c5125b5e42ebc18bd19474?bkt=p3-0000342369103a1f344a01edd5de6814a136&xcode=64c41dba00672d8fab1e661c89900ab31b0ca0154483d08c785e265d338e2ce4741d6fed08944017&fid=3341642904-250528-1061801715935247&time=1514042905&sign=FDTAXGERLQBHSK-DCb740ccc5511e5e8fedcff06b081203-oLS23CN0qiM%2FwyKYqwN7Z3va9pc%3D&to=d7&size=445145465&sta_dx=445145465&sta_cs=281&sta_ft=rar&sta_ct=6&sta_mt=6&fm2=MH,Yangquan,Anywhere,,shanghai,cnc&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000342369103a1f344a01edd5de6814a136&sl=79364174&expires=8h&rt=sh&r=554039205&mlogid=8279329328991083045&vbdid=-&fin=%E3%80%8CInnocent+flower%E3%80%8D%5BFLAC%5D.rar&rtype=1&dp-logid=8279329328991083045&dp-callid=0.1.1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=1&ut=6&uter=-1&serv=0&uc=2923846618&ic=653900195&ti=f8fdaa4589ff2f18fdcda624994d690368c2c497c036f221&by=themis`
`-> [HttpSkipResponseCommand.cc:231] errorCode=29 The response status is not successful. status=503`

在度盘的页面，助手有提示：“下载成功……”之类的。但web-ui中则是一如既往的：
 `remote server was unable to handle the request due to a temporary overloading or maintenance`
或者……
` HTTP response header was bad or unexpected`

直接使用导出的下载地址添加到aria2c中则会这样（几天前可行）：
`2017-12-23 23:06:59.293412 [ERROR] [AbstractCommand.cc:351] CUID#11 - Download aborted. URI=https://d11.baidupcs.com/file/0a5b6393d9c5125b5e42ebc18bd19474?bkt=p3-0000342369103a1f344a01edd5de6814a136&xcode=7b0f9ae80fdd34b1ffcf5937c5d371c81b0ca0154483d08ca61c27785ac566f0a5607bb37b46868f&fid=3341642904-250528-1061801715935247&time=1514041309&sign=FDTAXGERLQBHSKc-DCb740ccc5511e5e8fedcff06b081203-JJNc3JICTz3auDEzPnN1t%2BQuX3s%3D&to=d11&size=445145465&sta_dx=445145465&sta_cs=278&sta_ft=rar&sta_ct=6&sta_mt=6&fm2=MH,Yangquan,Anywhere,,shanghai,cnc&vuk=282335&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=0000342369103a1f344a01edd5de6814a136&sl=79364174&expires=8h&rt=sh&r=750996907&mlogid=8278900985269660983&vbdid=2309449705&fin=%E3%80%8CInnocent+flower%E3%80%8D%5BFLAC%5D.rar&fn=%E3%80%8CInnocent+flower%E3%80%8D%5BFLAC%5D.rar&rtype=1&dp-logid=8278900985269660983&dp-callid=0.1.1&hps=1&tsl=100&csl=100&csign=azJdY%2B10Z49b0LbASthGmxMFU9c%3D&so=0&ut=6&uter=4&serv=0&uc=1539727773&ic=653900195&ti=c1bc05e070ef2be96179b6d30275b500cc62259645b7e140&by=themis`
`Exception: [AbstractCommand.cc:351] errorCode=29 URI=http://www.baidupcs.com/403.html`
`-> [HttpSkipResponseCommand.cc:231] errorCode=29 The response status is not successful. status=503`

看这个错误日志，是度娘的锅？

RPC地址（其它配置默认）：http://token:nihao,shijie!@localhost:6800/jsonrpc
win10 家庭版 1709
chrome 63 （64位）
百度网盘助手 1.0.1
aria2配置：
`log=aria2.log`
`log-level=error`
`enable-rpc=true`
`rpc-allow-origin-all=true`
`rpc-listen-all=true`
`rpc-listen-port=6800`
`rpc-secret=nihao,shijie!`
`max-concurrent-downloads=5`
`continue=true`
`max-connection-per-server=6`
`min-split-size=10M`
`split=10`
`input-file=aria2.session`
`save-session=aria2.session`
`dir=C:\\Users\\xxx\\Downloads`
`file-allocation=falloc`

**Comment by bruceyaogit** [comment]
哪里都没动，今天成功了。。速度很给力！！
![downloading](https://user-images.githubusercontent.com/14084223/34323616-485fad0a-e88d-11e7-87bc-7599eae5821b.png)

**Comment by bruceyaogit** [comment]
这个问题原因知道了，是下载路径没有填的问题。
现在有一个新的问题，如果有两个RPC，下载路径怎么填？
![142](https://user-images.githubusercontent.com/14084223/34372564-a4f058dc-eb10-11e7-85be-4b0f609b3a12.png)

**Comment by bruceyaogit** [comment]
看到#494
